version: "3.9"

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins_terraform
    # Required for dockerd inside the container (nested cgroups / iptables).
    privileged: true
    ports:
      - "$J_HTTP_PORT:$J_HTTP_PORT"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - jenkins-docker-lib:/var/lib/docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS="--httpPort=${J_HTTP_PORT}"
    restart: unless-stopped

  gitea:
    image: gitea/gitea:1.25
    container_name: gitea
    environment:
      # Prevent UI setup wizard
      - GITEA__security__INSTALL_LOCK=true

      # Database config (required)
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db

      # Server settings
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:$G_HTTP_PORT/
      - GITEA__server__HTTP_PORT=$G_HTTP_PORT

      # Admin user (optional if using API / curl later)
      - G_USER=$G_USER
      - G_PASS=$G_PASS
      - G_EMAIL=$G_EMAIL
      - G_REPO_NAME=$G_REPO_NAME
    ports:
      - "$G_HTTP_PORT:$G_HTTP_PORT"
      - "2222:22"
    volumes:
      - ./gitea/init.sh:/init.sh
      - ./gitea/entrypoint.sh:/entrypoint.sh
    command: ["sh", "/entrypoint.sh"]

volumes:
  jenkins-docker-lib:
